//  Fetch all blogs
GET http://localhost:3003/api/blogs

###
//  Add a new blog 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 17
}

###
//  Delete a blog
DELETE http://localhost:3003/api/blogs/69a1b778dc4034beaa843fd8