GET http://localhost:3003/api/users

###
//  Add a new user 
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Idris",
    "name": "Idris Elba",
    "password": "password321"
}