//  Fetch all blogs
GET http://localhost:3003/api/blogs

###
//  Add a new blog 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 17
}

###
//  Delete a blog
DELETE http://localhost:3003/api/blogs/69aeaa09994ba601f283b267
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZ3VpcmUiLCJpZCI6IjY5YTZkYTFiOGVlYWIxNTdiOTA1YzQ2OCIsImlhdCI6MTc3Mzk0NjM0MSwiZXhwIjoxNzczOTQ5OTQxfQ.0GnKTNzh0Qv4xTvopclz-CGT9BoMPbBbCpZc8vyJ4h4

###
//  Update a blog
PUT http://localhost:3003/api/blogs/69a6da1b8eeab157b905c465
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 17
}

###