POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndpbnRlciIsImlkIjoiNjlhNDEzMWZlNmJlNjFhMTUxN2JjMDNkIiwiaWF0IjoxNzcyMzg0NTI4LCJleHAiOjE3NzIzODgxMjh9.DUDb_CffbV93zoC7x--22fJ41bl_gMLPo926v7hPA38

{
  "title": "Things fall apart",
  "author": "Nyungu wa thiong",
  "url": "https://afrikalainen kirja.com/",
  "likes": 19
}